export const externalPathsNPM = {
   '@typhonjs-svelte/lib/action': '@typhonjs-fvtt/runtime/svelte/action',
   '@typhonjs-svelte/lib/component/core': '@typhonjs-fvtt/runtime/svelte/component/core',
   '@typhonjs-svelte/lib/handler': '@typhonjs-fvtt/runtime/svelte/handler',
   '@typhonjs-svelte/lib/helper': '@typhonjs-fvtt/runtime/svelte/helper',
   '@typhonjs-svelte/lib/plugin/data': '@typhonjs-fvtt/runtime/svelte/plugin/data',
   '@typhonjs-svelte/lib/plugin/system': '@typhonjs-fvtt/runtime/svelte/plugin/system',
   '@typhonjs-svelte/lib/store': '@typhonjs-fvtt/runtime/svelte/store',
   '@typhonjs-svelte/lib/transition': '@typhonjs-fvtt/runtime/svelte/transition',
   '@typhonjs-svelte/lib/util': '@typhonjs-fvtt/runtime/svelte/util',

   '@typhonjs-fvtt/svelte/action': '@typhonjs-fvtt/runtime/svelte/action',
   '@typhonjs-fvtt/svelte/animate': '@typhonjs-fvtt/runtime/svelte/animate',
   '@typhonjs-fvtt/svelte/application': '@typhonjs-fvtt/runtime/svelte/application',
   '@typhonjs-fvtt/svelte/application/dialog': '@typhonjs-fvtt/runtime/svelte/application/dialog',
   '@typhonjs-fvtt/svelte/application/legacy': '@typhonjs-fvtt/runtime/svelte/application/legacy',
   '@typhonjs-fvtt/svelte/component/core': '@typhonjs-fvtt/runtime/svelte/component/core',
   '@typhonjs-fvtt/svelte/component/dialog': '@typhonjs-fvtt/runtime/svelte/component/dialog',
   '@typhonjs-fvtt/svelte/gsap': '@typhonjs-fvtt/runtime/svelte/gsap',
   '@typhonjs-fvtt/svelte/gsap/plugin': '@typhonjs-fvtt/runtime/svelte/gsap/plugin',
   '@typhonjs-fvtt/svelte/gsap/plugin/bonus': '@typhonjs-fvtt/runtime/svelte/gsap/plugin/bonus',
   '@typhonjs-fvtt/svelte/handler': '@typhonjs-fvtt/runtime/svelte/handler',
   '@typhonjs-fvtt/svelte/helper': '@typhonjs-fvtt/runtime/svelte/helper',
   '@typhonjs-fvtt/svelte/math': '@typhonjs-fvtt/runtime/svelte/math',
   '@typhonjs-fvtt/svelte/plugin/data': '@typhonjs-fvtt/runtime/svelte/plugin/data',
   '@typhonjs-fvtt/svelte/plugin/system': '@typhonjs-fvtt/runtime/svelte/plugin/system',
   '@typhonjs-fvtt/svelte/store': '@typhonjs-fvtt/runtime/svelte/store',
   '@typhonjs-fvtt/svelte/transition': '@typhonjs-fvtt/runtime/svelte/transition',
   '@typhonjs-fvtt/svelte/util': '@typhonjs-fvtt/runtime/svelte/util',

   // Exclude as external, but do not translate module references.
   'svelte': 'svelte',
   'svelte/animate': 'svelte/animate',
   'svelte/easing': 'svelte/easing',
   'svelte/internal': 'svelte/internal',
   'svelte/motion': 'svelte/motion',
   'svelte/store': 'svelte/store',
   'svelte/transition': 'svelte/transition'
};
